ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "uploadUrl" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "uploadType" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "expiresAt" TIMESTAMP(3);
ALTER TABLE "Post" ALTER COLUMN "url" SET DEFAULT '';
